import { Oswald } from "next/font/google";
import "./globals.css";

const oswald = Oswald({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ["latin"],
  display: 'swap',
});

export const metadata = {
  title: "Recipe Sharing Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${oswald.className} lg:mx-20`}>{children}</body>
    </html>
  );
}
